version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_compose
    restart: always
    ports:
      - 6606:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
  mongo:
    image: mongo:4
    container_name: mongo_compose
    restart: always
    ports:
      - 27017:27017
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: leanote
    #  MONGO_INITDB_ROOT_PASSWORD: leanote
    volumes:
        - ./mongo/data:/data/db
  nginx:
    image: nginx:1.14.0-alpine
    container_name: nginx_compose
    restart: always
    ports:
      - 80:80
      - 443:443
      - 5050:5050
      - 4040:4040
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/nginx.pid:/etc/nginx/nginx.pid
      - ./nginx/www:/etc/nginx/www
      - ./nginx/logs:/etc/nginx/logs
  leanote:
    image: zuolan/leanote
    container_name: leanote_app_compose
    restart: always
    ports:
      - 9000
    volumes:
      - ./leanote/conf/app.conf:/leanote/conf/app.conf
      - ./leanote/dataupload:/leanote/public/upload
    links:
      - mongo
      - nginx
  init_leanote_db:
    image: mongo:4
    links:
      - mongo
    volumes:
      - ./leanote/initdb.sh:/initdb.sh
      - ./leanote/mongodb_backup/leanote_install_data:/mongodb_backup/leanote_install_data
      - ./leanote/data:/data/db
    command: sh /initdb.sh
