version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_compose
    restart: always
    ports:
      - 6606:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      MYSQL_ROOT_PASSWORD: "123456" 
  nginx:
    image: nginx:1.14.0
    container_name: nginx_compose
    restart: always
    ports:
      - 80:80
      - 443:443
      - 5050:5050
      - 4040:4040
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/www:/etc/nginx/www
      - ./nginx/logs:/etc/nginx/logs
